### ISSUE TITLE
dev-robot: Remove GUI

### ISSUE THREAD

**Issue by ludusrusso** [robotrokers/rokers-yocto-distro#3]

**Comment by gmacario** [comment]
I am testing https://github.com/gmacario/genivi-dev-platform/tree/feat/add-jenkinsfile which will do `bitbake core-image-minimal` instead.

Rather than listing what you want to remove from `genivi-dev-platform`, I guess it will be much easier to instead list which package from `genivi-dev-platform` you will need to **add**.

**Comment by ludusrusso** [comment]
Yes it's true :D I close the issue
